### PR TITLE
update cleezy page ui

### PR DESCRIPTION
**Pull request by banyar-shin**
- match url shortener page with the style of user manager
- show date of creation on table now
- show alias as a hyperlink to the url, with the actual url shown below

### Before:
image

### After:
image

### CODE REVIEW

**Review by pnavab — COMMENTED** [review]
what is the bluebird import? i dont see it used can we remove that line

**Comment by banyar-shin** [comment]
removed bluebird line

**Review by pnavab — APPROVED** [review]
good

**Review by joshua-demo — APPROVED** [review]
Lgtm

**Pull request merged**
