### PR TITLE
Rebuild Home page

### PR DESCRIPTION
**Pull request by akshtshrma24**
When visiting the home page 
image

When scrolling down,
image

The sponsor us was replaced with this page
image

### CODE REVIEW

**Comment by akshtshrma24** [comment]
Please pull this and see for yourself still in the works, just pull it and look at it

**Review by danknessdra — APPROVED** [review]
i do not approve

**Review by danknessdra — APPROVED** [review]
rejected

**Comment by Luceium** [comment]
Are we planning to list the sponsor packages somewhere else?

**Review by evanugarte — COMMENTED** [review]
upload the png images to github cdn and use the URLs as the image`href`

**Comment by akshtshrma24** [comment]
> Are we planning to list the sponsor packages somewhere else?

ye

**Review by danknessdra — APPROVED** [review]
goood

**Review by Luceium — APPROVED** [review]
lgtm

**Review by evanugarte — APPROVED** [review]
lgtm good job dr awal

**Pull request merged**
