### PR TITLE
Scope CSS for `svg`s on login page

### PR DESCRIPTION
**Pull request by evanugarte**
@Luceium thanks for coming to the police station today, im detective spaghetti

do you know anything about this?

court admitted evidence 1:
image

court admitted evidence 2:
image

sounds to me like we dont know what scoped css is,

this pr fixes the layout:
image

also removed the border boxes and made the admin dashboard text indented off the edge of the page cause i felt like it
image

### CODE REVIEW

**Review by danknessdra — APPROVED** [review]
LGTM

**Review by ShaivPandya — APPROVED** [review]

**Review by hsorathia — APPROVED** [review]
ok that's sick i learned something new

**Review by NicholasLe04 — APPROVED** [review]
nice cascading style sheets

**Review by akshtshrma24 — APPROVED** [review]

**Review by Luceium — APPROVED** [review]
Thank you for bringing this to my attention. Your honor, I would like to bring up my accomplice @danknessdra who gave me an LGTM without looking at the code. We will test the code more thoroughly in the future 🫡.

**Pull request merged**
